apiVersion: v1
kind: Service
metadata:
  name: mario
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 30080
      targetPort: mario
      protocol: TCP
      name: http
  selector:
    app: mario